/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.uv.tpcs_practica03;

import java.util.Arrays;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ailton
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */

    private EntityManagerFactory entityManagerFactory;
    private EntityManager entityManager;
    private DetVentaDAO detVentaDAO;

    public GUI(EntityManagerFactory entityManagerFactory) {
        initComponents();
        this.entityManagerFactory = entityManagerFactory;
        detVentaDAO = new DetVentaDAO(entityManagerFactory.createEntityManager());
        DefaultTableModel tableModel = new DefaultTableModel();
        TableProducto.setModel(tableModel);
        tableModel.addColumn("ID Detalle Venta");
        tableModel.addColumn("ID Producto");
        tableModel.addColumn("ID Venta");
        tableModel.addColumn("Cantidad");
        tableModel.addColumn("Descripción");
        tableModel.addColumn("Precio");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TextFecha = new javax.swing.JTextField();
        BotonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableProducto = new javax.swing.JTable();
        BotonMasProducto = new javax.swing.JButton();
        BotonMenosProducto = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jSpinnerVenta = new javax.swing.JSpinner();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuNuevaVenta = new javax.swing.JMenu();
        MenuNuevoCliente = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Venta:");

        jLabel3.setText("Cliente:");

        jLabel4.setText("Fecha:");

        BotonBuscar.setBackground(new java.awt.Color(0, 204, 204));
        BotonBuscar.setForeground(new java.awt.Color(255, 255, 255));
        BotonBuscar.setText("Buscar");
        BotonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarActionPerformed(evt);
            }
        });

        TableProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Detalle Venta", "ID Producto", "ID Venta", "Cantidad", "Descripcion", "Precio"
            }
        ));
        jScrollPane1.setViewportView(TableProducto);

        BotonMasProducto.setBackground(new java.awt.Color(102, 255, 102));
        BotonMasProducto.setText("+");

        BotonMenosProducto.setBackground(new java.awt.Color(255, 51, 51));
        BotonMenosProducto.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSpinnerVenta)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonBuscar)
                                .addGap(132, 132, 132)
                                .addComponent(BotonMasProducto)
                                .addGap(30, 30, 30)
                                .addComponent(BotonMenosProducto)))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(TextFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSpinnerVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(BotonBuscar)
                    .addComponent(BotonMasProducto)
                    .addComponent(BotonMenosProducto)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        MenuNuevaVenta.setText("Nueva Venta");
        jMenuBar1.add(MenuNuevaVenta);

        MenuNuevoCliente.setText("Nuevo cliente");
        jMenuBar1.add(MenuNuevoCliente);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarActionPerformed
        // TODO add your handling code here:        
        System.out.println("Botón Buscar presionado");
    try {
        String idVentaString = jSpinnerVenta.getValue().toString();
        String idClienteString = jSpinner1.getValue().toString();
        Long idVenta = Long.parseLong(idVentaString);
        Long idCliente = Long.parseLong(idClienteString);

        System.out.println("ID Venta: " + idVenta);
        System.out.println("ID Cliente: " + idCliente);

        // Realiza la búsqueda en la base de datos utilizando DetVentaDAO
        List<DetVenta> detalles = detVentaDAO.obtenerDetallesVentaPorVentaCliente(idVenta, idCliente);

        // Antes de limpiar la tabla
        System.out.println("Cantidad de detalles encontrados: " + detalles.size());

        // Accede directamente al modelo de la tabla
        DefaultTableModel tableModel = (DefaultTableModel) TableProducto.getModel();

        // Agrega los detalles encontrados a la tabla
        for (DetVenta detalle : detalles) {
            tableModel.addRow(new Object[] {
                detalle.getIdDetVenta(), detalle.getProducto().getIdProducto(), detalle.getVenta().getIdVenta(),
                detalle.getCantidad(), detalle.getDescripcion(), detalle.getPrecio()
            });
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Ingresa IDs válidos para la venta y el cliente.");
    }
    }//GEN-LAST:event_BotonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
         EntityManagerFactory entityManagerFactory = HibernateUtil.getSessionFactory();
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            new GUI(entityManagerFactory).setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBuscar;
    private javax.swing.JButton BotonMasProducto;
    private javax.swing.JButton BotonMenosProducto;
    private javax.swing.JMenu MenuNuevaVenta;
    private javax.swing.JMenu MenuNuevoCliente;
    private javax.swing.JTable TableProducto;
    private javax.swing.JTextField TextFecha;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinnerVenta;
    // End of variables declaration//GEN-END:variables
}
